dist: Bionic
language: cpp
compiler: gcc
addons:
  apt:
    packages:
    - libboost-test-dev
    - gcc-8
    - g++-8
script:
- cmake . -DCMAKE_BUILD_TYPE=RELEASE
- cmake --build .                 
- cmake --build . --target test   
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T cpp_practice-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -Mortalitas1991:$BINTRAY_API_KEY "https://dl.bintray.com/mortalitas1991/cpp-deb/$TRAVIS_BUILD_NUMBER/cmake-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
